version: '3.9'

services:
  db:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=badapp
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
