version: '3.9'

services:
  evil-server:
    image: wiremock/wiremock:3.0.0-1
    volumes:
      - ./evil-server:/home/wiremock
    ports:
      - "8080:8080"
    command: ["--global-response-templating", "--verbose", "--disable-banner"]
