version: '3.9'

services:
  evil-server:
    image: wiremock/wiremock:3.1.0-1
    volumes:
      - ./environments/evil-server:/home/wiremock
    ports:
      - "8080:8080"
    command: ["--global-response-templating", "--verbose", "--disable-banner"]

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=badapp
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./environments/data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d badapp"]
      start_period: 5s
      interval: 3s
      retries: 2

  web:
    build:
      context: .
      dockerfile: environments/webapp/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
