# Generated by Django 4.2.5 on 2023-10-05 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_str", models.CharField(max_length=20, verbose_name="ID")),
                ("todo", models.CharField(max_length=100, verbose_name="todo")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="登録日"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="期限")),
            ],
            options={
                "db_table": "todos",
            },
        ),
    ]
